[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "dev-server"
path = "src/main.rs"

[dependencies]
# Pinned to match the highest stable 0.6.x version
leptos = { version = "*", features = ["csr"] }
leptos_router = { version = "*", features = ["csr"] }
# Logging for debugging
console_log = "1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
console_error_panic_hook = "0.1.7"
gloo-net = { version = "*", features = ["json"] }
chrono = { version = "*", features = ["serde"] }
common = { path = "../common", features = ["ssr"] }

[features]
ssr = [
  "leptos/ssr",
  "leptos_router/ssr",
  "dep:leptos_axum",
  "dep:tokio",
  "dep:sqlx",
  "dep:axum"
]

[dependencies.leptos_axum]
version = "*"
optional = true

[dependencies.tokio]
version = "1"
features = ["full"]
optional = true

[dependencies.sqlx]
version = "*"
features = ["runtime-tokio-rustls", "postgres", "chrono"]
optional = true

[dependencies.axum]
version = "*"
optional = true

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z' # Optimize for size (WASM)

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
# Fixes WASM runtime error by using browser's JS-based randomness source
getrandom = { version = "0.2", features = ["js"] }
